PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE android_metadata (locale TEXT);
INSERT INTO android_metadata VALUES('ar_EG');
CREATE TABLE `alsibha` (`id` INTEGER NOT NULL, `text` TEXT, `max` INTEGER NOT NULL, `total` INTEGER NOT NULL, `current_7` INTEGER NOT NULL, `current_33` INTEGER NOT NULL, `current_100` INTEGER NOT NULL, `current_c` INTEGER NOT NULL, `position` INTEGER NOT NULL, `current` INTEGER NOT NULL, PRIMARY KEY(`id`));
INSERT INTO alsibha VALUES(0,'الْلَّهُ أَكْبَرُ',0,0,0,0,0,0,0,0);
INSERT INTO alsibha VALUES(1,'الْحَمْدُ للّهِ',0,0,0,0,0,0,0,0);
INSERT INTO alsibha VALUES(2,'سُبْحَانَ اللَّهِ',0,0,0,0,0,0,0,0);
INSERT INTO alsibha VALUES(3,'سُبْحَانَ اللَّهِ وَبِحَمْدِهِ ، سُبْحَانَ اللَّهِ الْعَظِيمِ',0,0,0,0,0,0,0,0);
INSERT INTO alsibha VALUES(4,'سُبْحَانَ اللهِ العَظِيمِ وَبِحَمْدِهِ',0,0,0,0,0,0,0,0);
INSERT INTO alsibha VALUES(5,'لَا إلَه إلّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلُّ شَيْءِ قَدِيرِ.',0,0,0,0,0,0,0,0);
INSERT INTO alsibha VALUES(6,'لا حَوْلَ وَلا قُوَّةَ إِلا بِاللَّهِ ',0,0,0,0,0,0,0,0);
INSERT INTO alsibha VALUES(7,'الْلَّهُم صَلِّ وَسَلِم وَبَارِك عَلَى سَيِّدِنَا مُحَمَّد',0,0,0,0,0,0,0,0);
INSERT INTO alsibha VALUES(8,'أستغفر الله',0,0,0,0,0,0,0,0);
INSERT INTO alsibha VALUES(9,'سُبْحَانَ الْلَّهِ، وَالْحَمْدُ لِلَّهِ، وَلَا إِلَهَ إِلَّا الْلَّهُ، وَالْلَّهُ أَكْبَرُ',0,0,0,0,0,0,0,0);
INSERT INTO alsibha VALUES(10,'لَا إِلَهَ إِلَّا اللَّه',0,0,0,0,0,0,0,0);
INSERT INTO alsibha VALUES(11,'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ , وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ , اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ.',0,0,0,0,0,0,0,0);
INSERT INTO alsibha VALUES(12,'لَا إلَه إلّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلُّ شَيْءِ قَدِيرِ.',0,0,0,0,0,0,0,0);
INSERT INTO alsibha VALUES(13,'لا حَوْلَ وَلا قُوَّةَ إِلا بِاللَّهِ',0,0,0,0,0,0,0,0);
INSERT INTO alsibha VALUES(14,'أستغفر الله',0,0,0,0,0,0,0,0);
CREATE TABLE room_master_table (id INTEGER PRIMARY KEY,identity_hash TEXT);
INSERT INTO room_master_table VALUES(42,'588461ae14f405a76e5ffe711cb07be0');
COMMIT;